"""add_access_case_reactive_fields

Revision ID: 995e17c86849
Revises: a44c2705472c
Create Date: 2026-04-18 23:29:30.834324+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '995e17c86849'
down_revision: Union[str, None] = 'a44c2705472c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_cases', sa.Column('student_cpf', sa.String(), nullable=True))
    op.add_column('access_cases', sa.Column('search_attempts', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_cases', 'search_attempts')
    op.drop_column('access_cases', 'student_cpf')
    # ### end Alembic commands ###
