upstream api_backend { server 127.0.0.1:8001; }
upstream web_backend { server 127.0.0.1:3001; }

server {
    listen 8000;
    location / {
        proxy_pass         http://api_backend;
        proxy_http_version 1.1;
        proxy_set_header   Connection "";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }
}

server {
    listen 3000;
    location / {
        proxy_pass         http://web_backend;
        proxy_http_version 1.1;
        proxy_set_header   Connection "";
        proxy_set_header   Host $host;
    }
}
