"""add_access_cases_table

Revision ID: a44c2705472c
Revises: 27a1ce6ae065
Create Date: 2026-04-18 23:15:27.694857+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a44c2705472c'
down_revision: Union[str, None] = '27a1ce6ae065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('purchase_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('access_link', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('access_confirmed', sa.Boolean(), nullable=False),
    sa.Column('scheduled_d1_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    op.create_index('idx_access_cases_account_contact', 'access_cases', ['account_id', 'contact_id'], unique=False)
    op.create_index(op.f('ix_access_cases_account_id'), 'access_cases', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_cases_account_id'), table_name='access_cases')
    op.drop_index('idx_access_cases_account_contact', table_name='access_cases')
    op.drop_table('access_cases')
    # ### end Alembic commands ###
